### ISSUE TITLE
Lack of readme, trained models, and used datasets.

### ISSUE THREAD

**Issue by Fujiaoji** [JehLeeKR/Adversarial-phishing-logos#1]
Hello,

I am wondering if you can add some introductions for each file. Besides, I find that there also lack of trained models and dataset. Do you mind to share these information. Thanks

**Comment by LetsBeSecure** [comment]
Hi,
Could you please share the file format of the cls_train.txt and cls_test.txt, which would help me to analyse the dataloader_v2.py file?
Thanks

**Comment by Fujiaoji** [comment]
> Hello,
> 
> I am wondering if you can add some introductions for each file. Besides, I find that there also lack of trained models and dataset. Do you mind to share these information. Thanks

Thanks for the sharing

**Comment by Fujiaoji** [comment]
> Hi, Could you please share the file format of the cls_train.txt and cls_test.txt, which would help me to analyse the dataloader_v2.py file? Thanks

Sorry for the late reply, I think the authors have shared the code for data, like src/file_manage.ipynb

**Comment by LetsBeSecure** [comment]
Thank you for the response.
