### ISSUE TITLE
Request for Model Parameters and Dataset

### ISSUE THREAD

**Issue by lzclzclzc12** [JehLeeKR/Adversarial-phishing-logos#2]
Dear Jehyun Lee,

I hope this message finds you well. I am currently working on a project related to your paper, and I would like to request some additional resources for further research.

Could you kindly provide the following:
- The trained parameters for the Discriminator and Generator models mentioned in your paper.
- The dataset used in the experiments (as referred to in Section 5.1 of the paper), specifically the logos of protected and unprotected brands.

I believe these resources would greatly assist in replicating your results and exploring the effectiveness of your proposed methods.

Thank you very much for your time and assistance!

Best regards,
lzc

**Comment by JehLeeKR** [comment]
Dear Izc,

Thank you for your interest in our work.

Please drop an email to jehyunleekr(at)gmail.com 

It is too huge to upload the logo files in a repository.

Thank you.

**Comment by lzclzclzc12** [comment]
> Dear Izc,
> 
> Thank you for your interest in our work.
> 
> Please drop an email to jehyunleekr(at)gmail.com
> 
> It is too huge to upload the logo files in a repository.
> 
> Thank you.

Thank you for providing the dataset.
